import { ArrowClockwise, ArrowRight, ClipboardText, MagnifyingGlass, WarningCircle } from "@phosphor-icons/react";
import { useMemo, useState } from "react";
import { questions } from "../data/questions";
import type { MistakeRecord } from "../types";

export function MistakeLog({ mistakes, onRetry }: { mistakes: MistakeRecord[]; onRetry: (questionId: string) => void }) {
  const [filter, setFilter] = useState("all");
  const shown = useMemo(() => mistakes.filter((mistake) => filter === "all" || mistake.module === filter), [filter, mistakes]);
  const modules = [...new Set(mistakes.map((mistake) => mistake.module))];
  return <div className="mistake-page"><section className="page-intro intro-inline"><div><span className="section-kicker">Foutenlog</span><h1>Fouten zijn je persoonlijk studieplan.</h1><p>Niet om af te vinken, wel om te begrijpen: wat ging er mis en wat doe je volgende keer anders?</p></div><div className="error-count"><WarningCircle size={27} weight="fill" /><strong>{mistakes.length}</strong><span>opgeslagen fouten</span></div></section><section className="mistake-toolbar"><div className="filter-tabs small-tabs"><button className={filter === "all" ? "active" : ""} onClick={() => setFilter("all")}>Alles</button>{modules.map((module) => <button key={module} className={filter === module ? "active" : ""} onClick={() => setFilter(module)}>{module}</button>)}</div><span><MagnifyingGlass size={16} /> lokaal opgeslagen op dit apparaat</span></section>{shown.length ? <section className="mistake-table">{shown.map((mistake) => { const question = questions.find((item) => item.id === mistake.questionId); return <article className="mistake-entry" key={mistake.id}><span className="error-marker">×</span><div className="mistake-core"><div className="mistake-meta"><span>{mistake.module}</span><span>{mistake.topic}</span><time>{new Date(mistake.createdAt).toLocaleDateString("nl-NL", { day: "2-digit", month: "short", year: "numeric" })}</time></div><h2>{question?.question ?? "Vraag uit eerdere oefensessie"}</h2><p><strong>Fouttype:</strong> {mistake.faultType}</p>{mistake.reflection && <p className="reflection-note"><ClipboardText size={16} /> <em>{mistake.reflection}</em></p>}</div><button className="secondary-button" onClick={() => onRetry(mistake.questionId)}><ArrowClockwise size={18} /> Opnieuw oefenen</button></article>; })}</section> : <div className="practice-empty"><WarningCircle size={30} /><h2>Je foutenlog is nog leeg.</h2><p>Wanneer je een oefenvraag als ‘nog oefenen’ markeert, verschijnt hij hier met jouw reflectie.</p></div>}<div className="mistake-footnote"><ArrowRight size={18} /><p>Een fout blijft staan als leerspoor. Maak hem opnieuw in <strong>Oefenen</strong> om te zien of je aanpak nu werkt.</p></div></div>;
}
